export {default as Navbar } from './Navbar/Navbar';
export {default as Products } from './Products/Products';
export {default as Skincare } from './Products/skincare';
export {default as Makeup } from './Products/makeup';
export {default as Perfume } from './Products/perfume';
export {default as Cart } from './Cart/Cart';
export {default as Front} from './Front/Front';
export {default as Quotes} from './Front/Quotes';
export {default as Footer} from './Footer/Footer';
export {default as ProductView} from './Products/Product/ProductView';
export {default as Checkout} from './CheckoutForm/Checkout/Checkout';
export {default as Contact} from './Contact/Contact';
export {default as Team} from './Team/Team';